# Generated by Django 5.1.2 on 2024-11-08 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemateAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('aone', 'AngelOne')], default='aone', max_length=20)),
                ('brokerConfig', models.JSONField()),
            ],
            options={
                'verbose_name': 'Demate Account',
                'verbose_name_plural': 'Demate Accounts',
            },
        ),
    ]
